name: audit-inspection-clause-extractor
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - langchain
      - docx
      - python-docx
      - unstructured
      - openpyxl
      - groq
      - pypdf